title: Demi+; gedemineraliseerd water gemaakt van regenwater.
email: info@demiplus.nl
description: >- # this means to ignore newlines until "baseurl:"
  Om het gebruik van drinkwater voor de schoonmaakbranche terug te dringen, produceren wij gedemineraliseerd water van hemelwater.
  We noemen het Demi+; ‘ Groen’ water voor de schoonmaakbranche.
  Demi+ voldoet aan alle kwaliteits- en veiligheidseisen om binnen en buiten te reinigen.
baseurl: "" # the subpath of your site, e.g. /blog
domain: demiplus.nl
url: "https://www.demiplus.nl" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: demiplus_nl
github_username:  jekyll
ga4_id: "G-G0NPH94YQC"

# Build settings
#theme: minima
plugins:
  - jekyll-feed

collections:
  locaties:
    output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - readme.md
  - CNAME
  - makefile
  - themes/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
